// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"means/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getUserInfo",
				Handler: getUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addUser",
				Handler: addUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
