// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
}

type GetUserReq struct {
	Id int64 `json:"userInfo"`
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type AddUserReq struct {
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
}
